print("       ☆")
print("      xxx")
print("     x⍟xx")
print("    xxx⍟xx")
print("   xx⍟xxx⍟x")
print("  xx⍟xx⍟xO⍟")
print(" xxx⍟xxxx⍟xxx")
print("xxxxxxxxxxxxxxx")
print("       xx")
print("       xx")
print("      xxxx")
